
name: CICD

on: 
 push: 
   branches: [master]

jobs:
 build:
   runs-on:[ubuntu-latest]
   steps:
     - name: Checkout source
       uses: actions/checkout@v3
     - name: Setup Java
       uses: actions/setup-java@v3
       with:
         distribution: 'temurin'
         java-version: '17'
      - name: Build Project
        run: mvn clean install -DskipTests
      - name: Login to docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Buil Docker image
        run: docker build -t demo/spring-boot-example .
      - name: publish image to docker hub
        run: docker push demo/springboot-example:latest

deploy:
  needs: build
  runs-on: [aws-ec2]
  steps:
    - name: Pull image from the docker hub
      run: docker pull demo/springboot-example:latest
    - name: delete old container
      run: docker rm -f springboot-example-container
    - name: run docker container
      run: docker run -d -p 9090:9090 --name springboot-example-container demo/springboot-example
       
